### ISSUE TITLE
testphp file update

### ISSUE THREAD

**Issue by Emily23805** [PlavorSeol/Helloworld#4]
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Hello, world!</title>
  </head>
  <body>
  <h1>PHP test </h1>
  <q>PHP echo test</q>
<?php echo "Hello, world!"; ?>
  <q>PHP echo test ko-kr (country : Republic of Korea)</q>
  <?php echo "안녕하세요"; ?>
  <h2>js test line</h2>
  <q>server time</q>
  <script>
    var now = now Date();
    var display = now.toLocalString();
    document.weite(display)
  </script>
  <q>what is to days info?</q>
  <script typt="text/javascript">
    var now Date()
    document.weite("today is")
    document.weite(now.getYear() + "year")
    document.weite((now.getMonth()+1) + "Month")
    document.weite(now.getDate() + "date")
    </script>
  <h3>PHP info</h3>
  <?php phpinfo(); ?>
  </body>
</html>
더 많은 확장을 달음 (PHP JS HTML 문서 기본기능및 유효성 점검등등)

**Comment by PlavorSeol** [comment]
DIY
